export const songs = [
    { artistName: "Ariana Grande", songName: "Thank U, Next", songImg: "", textForLerik: "Доброе утро! Пусть день будет таким же ярким, как твоя улыбка." },
    { artistName: "Ariana Grande", songName: "No Tears Left to Cry", songImg: "", textForLerik: "Ты сегодня просто волшебная! Пусть весь мир будет твоим." },
    { artistName: "Ariana Grande", songName: "7 Rings", songImg: "", textForLerik: "Привет, красавица! Ты словно солнце, согреваешь всех вокруг!" },
    { artistName: "Ariana Grande", songName: "Into You", songImg: "", textForLerik: "Ты как магнит, невозможно не восхищаться! Пусть день будет твоим!" },
    { artistName: "Ariana Grande", songName: "Problem", songImg: "", textForLerik: "Ты просто невероятна. Пусть этот день принесет тебе радость!" },
    { artistName: "Lida", songName: "Лада Турбо Спейс", songImg: "", textForLerik: "Твой стиль – это чистый кайф! Удачного дня, как всегда!" },
    { artistName: "Lida", songName: "Нихао", songImg: "", textForLerik: "Ты невероятна, как и твоя энергия! Хорошего дня!" },
    { artistName: "Lida", songName: "Лох", songImg: "", textForLerik: "Ты как живое солнце, озаряешь всех вокруг. Пусть день будет ярким!" },
    { artistName: "Lida", songName: "ЧСВ", songImg: "", textForLerik: "Ты как всегда будоражишь чувства! Пусть день будет волшебным." },
    { artistName: "Lida", songName: "Герда", songImg: "", textForLerik: "Ты как лучик света в этот мир. Желаю, чтобы твой день был именно таким!" },
    { artistName: "Arctic Monkeys", songName: "Do I Wanna Know?", songImg: "", textForLerik: "Привет, чудо! В этот день твоя харизма сияет особенно ярко!" },
    { artistName: "Arctic Monkeys", songName: "R U Mine?", songImg: "", textForLerik: "Ты как всегда удивляешь! Пусть день будет таким же необычным." },
    { artistName: "Arctic Monkeys", songName: "Why'd You Only Call Me When You're High?", songImg: "", textForLerik: "Ты всегда в центре внимания, как звезда! Пусть день будет твоим." },
    { artistName: "Arctic Monkeys", songName: "I Bet You Look Good on the Dancefloor", songImg: "", textForLerik: "Ты словно огонь, привлекаешь внимание. Пусть день будет невероятным!" },
    { artistName: "Arctic Monkeys", songName: "Arabella", songImg: "", textForLerik: "Твоя энергия — это просто магия. Пусть день будет таким же вдохновляющим!" },
    { artistName: "Linkin Park", songName: "In the End", songImg: "", textForLerik: "Ты как бриллиант, сверкаешь в любой день. Улыбайся чаще!" },
    { artistName: "Linkin Park", songName: "Numb", songImg: "", textForLerik: "Ты великолепна, не забывай об этом! Пусть твой день будет лёгким." },
    { artistName: "Linkin Park", songName: "Crawling", songImg: "", textForLerik: "Ты как вдохновение для лучших песен. Пусть этот день будет твоим!" },
    { artistName: "Linkin Park", songName: "Faint", songImg: "", textForLerik: "Ты как горящий огонь. Пусть твой день будет ярким и красивым!" },
    { artistName: "Linkin Park", songName: "One Step Closer", songImg: "", textForLerik: "Ты как источник силы, ты невероятна! Пусть день будет успешным." },
    { artistName: "Пошлая Молли", songName: "Контракт", songImg: "", textForLerik: "Ты как самая красивая глава в книге. Хорошего дня!" },
    { artistName: "Пошлая Молли", songName: "Беспечный Рыцарь Тьмы", songImg: "", textForLerik: "Ты словно вдохновение для лучших песен. Пусть день будет твоим!" },
    { artistName: "Пошлая Молли", songName: "Адская Колыбельная", songImg: "", textForLerik: "Ты как рок-звезда, с каждым днем становишься только круче!" },
    { artistName: "Пошлая Молли", songName: "Ханнамонтана", songImg: "", textForLerik: "Ты — моя личная муза, лучший комплимент для тебя — твоя улыбка!" },
    { artistName: "Пошлая Молли", songName: "Райские цветы", songImg: "", textForLerik: "Ты просто загадка, которая делает этот мир ярче! Пусть день будет чудесным." },
    { artistName: "ЛСП", songName: "Монетка", songImg: "", textForLerik: "Ты идеальна. Пусть этот день принесет тебе только радость." },
    { artistName: "ЛСП", songName: "Белый Танец", songImg: "", textForLerik: "В мире нет более прекрасной души, чем твоя. Удачного дня!" },
    { artistName: "ЛСП", songName: "Ползать", songImg: "", textForLerik: "Ты как время, которое всегда ценно. Пусть этот день будет особенным!" },
    { artistName: "ЛСП", songName: "Порнозвезда", songImg: "", textForLerik: "Ты как вдохновение для поэтов. Пусть твой день будет красивым!" },
    { artistName: "ЛСП", songName: "МЛД", songImg: "", textForLerik: "Ты словно мой свет в темном мире. Пусть день будет ярким!" },
    { artistName: "Maneskin", songName: "Beggin'", songImg: "", textForLerik: "Ты как огонь, всегда привлекаешь внимание. Пусть этот день будет ярким!" },
    { artistName: "Maneskin", songName: "Zitti e buoni", songImg: "", textForLerik: "Ты как громкая песня, всегда запоминаешься. Желаю прекрасного дня!" },
    { artistName: "Maneskin", songName: "I Wanna Be Your Slave", songImg: "", textForLerik: "Ты как шторм, пронизываешь все вокруг. Пусть твой день будет безумно хорош!" },
    { artistName: "Maneskin", songName: "Torna a casa", songImg: "", textForLerik: "Ты, как громкое вдохновение для серых дней. Пусть день будет наполнен светом!" },
    { artistName: "Maneskin", songName: "Levita", songImg: "", textForLerik: "Ты как радуга после дождя. Пусть твой день будет разноцветным и радостным!" },
    { artistName: "Кишлак", songName: "Я Уебываю в джаз", songImg: "", textForLerik: "Твоя улыбка всегда делает день особенным. Будь счастлива!" },
    { artistName: "Кишлак", songName: "Самый лучший день", songImg: "", textForLerik: "Ты как звезда на небе, так ярко сияешь. Пусть день будет твоим!" },
    { artistName: "Кишлак", songName: "Слёзы", songImg: "", textForLerik: "Ты — мой самый приятный сюрприз. Пусть этот день будет волшебным!" },
    { artistName: "Кишлак", songName: "Эй", songImg: "", textForLerik: "Ты как огонь, твоя энергия заражает всех вокруг. Пусть день будет твоим!" },
    { artistName: "Кишлак", songName: "Накуримся Напьемся", songImg: "", textForLerik: "Ты как весенний дождик, всегда даришь свежесть. Пусть день будет лёгким!" },
    { artistName: "Валентин Стрыкало", songName: "Улица Сталеваров", songImg: "", textForLerik: "Ты невероятно притягиваешь внимание. Пусть этот день будет твоим!" },
    { artistName: "Скриптонит", songName: "Это любовь", songImg: "", textForLerik: "Ты невероятно притягиваешь внимание. Пусть этот день будет твоим!" },
    { artistName: "Валентин Стрыкало", songName: "Кайен", songImg: "", textForLerik: "Ты моя радость! Пусть в этот день сбудется всё, что ты хочешь." },
    { artistName: "Валентин Стрыкало", songName: "Фанк", songImg: "", textForLerik: "Ты как праздник в этот мир. Пусть твой день будет ярким и запоминающимся!" },
    { artistName: "Валентин Стрыкало", songName: "Наше Лето", songImg: "", textForLerik: "Ты как мечта, которая сбывается. Пусть твой день будет потрясающим!" },
    { artistName: "Валентин Стрыкало", songName: "Ты не такая", songImg: "", textForLerik: "Ты как светлый лучик в темном мире. Желаю тебе только счастья!" },
    { artistName: "The Neighbourhood", songName: "Sweater Weather", songImg: "", textForLerik: "Ты как весна после долгой зимы! Пусть день будет солнечным." },
    { artistName: "The Neighbourhood", songName: "Afraid", songImg: "", textForLerik: "Твоя улыбка – это магия. Желаю волшебного дня!" },
    { artistName: "The Neighbourhood", songName: "R.I.P. 2 My Youth", songImg: "", textForLerik: "Ты как лучший сон, который становится реальностью. Пусть твой день будет таким же чудесным!" },
    { artistName: "The Neighbourhood", songName: "Baby Come Home", songImg: "", textForLerik: "Ты как звезда, которая освещает ночное небо. Пусть твой день будет таким же ярким!" },
    { artistName: "The Neighbourhood", songName: "Stargazing", songImg: "", textForLerik: "Ты как загадка, которую хочется разгадать. Пусть день будет удивительным!" },
    { artistName: "Серега Пират", songName: "Почему ты еще не фанат", songImg: "", textForLerik: "Ты как огонь в холодный день. Пусть твой день будет горячим!" },
    { artistName: "Серега Пират", songName: "Маша", songImg: "", textForLerik: "Ты как загадка, которую хочется разгадать. Удачного дня!" },
    { artistName: "Серега Пират", songName: "Вайбмен", songImg: "", textForLerik: "Ты как летний дождик, освежаешь всё вокруг. Пусть день будет свежим и ярким!" },
    { artistName: "Серега Пират", songName: "Зомби-апокалипсис", songImg: "", textForLerik: "Ты как музыка, которая запоминается. Пусть твой день будет таким же!" },
    { artistName: "Серега Пират", songName: "Мой байк", songImg: "", textForLerik: "Ты — мой самый любимый момент в жизни. Пусть день будет твоим!" },
    { artistName: "CMH", songName: "SWIFT?", songImg: "", textForLerik: "Ты заставляешь мир вращаться вокруг себя! Пусть твой день будет легким." },
    { artistName: "CMH", songName: "Стикер", songImg: "", textForLerik: "Ты как мелодия, всегда в сердце! Пусть день будет твоим!" },
    { artistName: "CMH", songName: "Люби меня", songImg: "", textForLerik: "Ты как светлый лучик. Пусть твой день будет таким же!" },
    { artistName: "CMH", songName: "milf money", songImg: "", textForLerik: "Ты как звезда, всегда на высоте. Пусть твой день будет чудесным!" },
    { artistName: "CMH", songName: "Прицел", songImg: "", textForLerik: "Ты как сила, которая наполняет этот мир. Пусть твой день будет полон энергии!" },
    { artistName: "DK", songName: "PRAXX", songImg: "", textForLerik: "Ты словно лето в душе! Пусть день принесет только радость." },
    { artistName: "DK", songName: "2k", songImg: "", textForLerik: "Ты как яркая звезда на этом свете. Пусть день будет сияющим!" },
    { artistName: "DK", songName: "Ночь", songImg: "", textForLerik: "Ты — лучший момент в моем дне! Пусть день будет твоим!" },
    { artistName: "DK", songName: "Не сей любовь", songImg: "", textForLerik: "Ты как волшебный свет. Пусть этот день принесет тебе волшебство!" },
    { artistName: "DK", songName: "Ты меня не ищи", songImg: "", textForLerik: "Ты как лето, всегда в сердце. Пусть день будет наполнен радостью!" },
    { artistName: "Justin Bieber", songName: "Peaches", songImg: "", textForLerik: "Ты как небо после дождя, так свежа и ярка. Желаю счастья в этот день!" },
    { artistName: "Justin Bieber", songName: "Sorry", songImg: "", textForLerik: "Ты как вдохновение для лучших песен. Пусть твой день будет чудесным!" },
    { artistName: "Justin Bieber", songName: "Yummy", songImg: "", textForLerik: "Ты как сладость, которая делает этот мир вкуснее. Пусть день будет твоим!" },
    { artistName: "Justin Bieber", songName: "Intentions", songImg: "", textForLerik: "Ты как бриллиант, сияющий в этом мире. Пусть день будет ярким и незабываемым!" },
    { artistName: "Justin Bieber", songName: "Holy", songImg: "", textForLerik: "Ты как ангел, посланный с небес. Пусть твой день будет полон счастья!" },
    { artistName: "FACE", songName: "ЮМОРИСТ", songImg: "", textForLerik: "Ты как весенний дождик, всегда даришь свежесть. Пусть день будет лёгким!" },
    { artistName: "FACE", songName: "Лиза", songImg: "", textForLerik: "Ты лучшая, не забывай об этом. Пусть день принесет много счастья!" },
    { artistName: "FACE", songName: "Антидепрессант", songImg: "", textForLerik: "Ты как золото, сияешь ярче всех! Пусть день будет твоим!" },
    { artistName: "FACE", songName: "24 на 7 ", songImg: "", textForLerik: "Ты как рай, который я так ждал. Пусть день будет божественно хорош!" },
    { artistName: "FACE", songName: "Vlone", songImg: "", textForLerik: "Ты как свет в темной комнате. Пусть твой день будет полон радости!" }
];
